# config.yaml
base_dir: "C:/wAllICzech"
paths:
  output_dir: "output"
  logs_dir: "logs"
  presets_dir: "presets/user_presets"
  projects_dir: "projects"
  models_dir: "ai_models"
  tools_dir: "tools"

server:
  host: "0.0.0.0"
  port: 7860

models:
  diffusers:
    flux:
      base_model: "ai_models/Flux/flux.1Dev.safetensors"
      default_prompt: "A beautiful landscape, highly detailed, photorealistic"
      default_negative_prompt: "blurry, low quality, distorted"
      default_steps: 50
      default_guidance_scale: 7.5
      default_strength: 0.8
    sdxl:
      base_model: "ai_models/Diffusers/sdxl_base_1.0.safetensors"
      default_prompt: "A stunning portrait, cinematic lighting"
      default_negative_prompt: "blurry, low quality, overexposed"
      default_steps: 30
      default_guidance_scale: 7.0
      default_strength: 0.75
  wav2lip:
    quality: "high"
    nosmooth: true
    padding: [0, 20, 0, 0]
    models:
      standard: "ai_models/Lipsync/wav2lip.pth"
      gan: "ai_models/Lipsync/wav2lip_gan.pth"
      expert: "ai_models/Lipsync/lipsync_expert.pth"
      encoder: "ai_models/Lipsync/audio_visual_encoder.pth"
  face_detection:
    resnet50: "ai_models/Forensic/detection_Resnet50_Final.pth"
    mobilenet: "ai_models/Forensic/detection_mobilenet0.25_Final.pth"
    yolov5l: "ai_models/yolo/yolov5l-face.pth"
    yolov5n: "ai_models/yolo/yolov5n-face.pth"
    s3fd: "ai_models/FaceDetection/s3fd-619a316812.pth"
  landmarks:
    dlib: "ai_models/FaceDetection/shape_predictor_68_face_landmarks.dat"
    test_eyes_mouth: "ai_models/Utils/test_eye_mouth_landmarks.pth"
  faceswap:
    model: "ai_models/FaceDetection/inswapper_128.onnx"
  segmentation:
    parsenet: "ai_models/Forensic/parsing_parsenet.pth"
    sam_base: "ai_models/Segmentation/sam_vit_b_01ec64.pth"
    sam_high: "ai_models/Segmentation/sam_vit_h_4b8939.pth"
    grounding_dino_b: "ai_models/Segmentation/groundingdino_swinb_cogcoor.pth"
    grounding_dino_t: "ai_models/Segmentation/groundingdino_swint_ogc.pth"
  real_esrgan:
    model: "ai_models/Upscaler/4x-UltraSharp.pth"
    fallback: "ai_models/Upscaler/RealESRGAN_x4plus.pth"
    arch: "4x-UltraSharp"
    scale: 4
    tile: 512
    tile_pad: 10
    pre_pad: 0
    half: true
  codeformer:
    model: "ai_models/Upscaler/codeformer.pth"
  gfpgan:
    model: "ai_models/Upscaler/GFPGANv1.4.pth"
    detection: "ai_models/Forensic/detection_Resnet50_Final.pth"
    parsing: "ai_models/Forensic/parsing_parsenet.pth"
  quality:
    visual_disc: "ai_models/Generative/visual_quality_disc.pth"
    vgg_feature: "ai_models/Upscaler/vgg.pth"
  generative:
    spade: "ai_models/Generative/spade_generator.pth"
    sgd: "ai_models/Generative/sgd_NNRT_model_epoch19008_50000.pth"
    taesd_encoder: "ai_models/Generative/taesdxl_encoder.pth"
    taesd_decoder: "ai_models/Generative/taesdxl_decoder.pth"
  tracking:
    motion: "ai_models/Tracking/motion_extractor.pth"
    warp: "ai_models/Tracking/warping_module.pth"
    stitch: "ai_models/Tracking/stitching_retargeting_module.pth"
    camera: "ai_models/Tracking/camera_graph.pth"
    raft: "ai_models/Tracking/raft-small.pth"
  vocal_remover:
    baseline: "ai_models/Utils/baseline.pth"
  identity:
    feature_extractor: "ai_models/Utils/appearance_feature_extractor.pth"
    icp_data: "ai_models/Utils/icp_data.pth"

gui:
  default_zoom: 1.0
  max_fps: 60
  supported_formats:
    images: [".jpg", ".jpeg", ".png", ".tiff", ".webp"]
    videos: [".mp4", ".avi", ".mov"]
    audio: [".wav", ".mp3"]
  smile_range:
    min: -1.0
    max: 1.0
  mouth_open_range:
    min: 0.0
    max: 1.0
  eyebrow_raise_range:
    min: -0.5
    max: 0.5
  eye_open_range:
    min: 0.0
    max: 1.0

logging:
  level: "INFO"
  file: "logs/app.log"