name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    if: false # disabled in favor of gh-pages-branch.yml (main -> gh-pages)
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: echo "Use .github/workflows/gh-pages-branch.yml (main -> gh-pages)"
